### ISSUE TITLE
Undocumented endpoint to get original link url?

### ISSUE THREAD

**Issue by buritica** [BranchMetrics/Deferred-Deep-Linking-Public-API#14]
Hi,

**some context**
In order to implement our custom landing pages, we needed to get some of the info that was used to create the branch link to show user name and photo form the landing. since the only thing we have available from the web after a successful redirection is the `_branch_match_id` and not the complete branch url, we are calling `/v1/url` with this `_branch_match_id`. This returns the original url, which we can then use to call the same endpoint, and get the original data.

**question/bug**
- since this API functionality is not documented, can we actually rely on it to get the original url?
- if not, what is the best way for us to get the original information from the `_branch_match_id?`

thanks

cc @julian-amaya, @jseros

**Comment by dskatz22** [comment]
I also am interested in this info

**Comment by aaustin** [comment]
Sorry guys - I'm sorry this wasn't answered before. We don't have proper alerts set on this repository. I'm surprised that even works actually.

In order to retrieve the referring link data from your site, please use the web SDK initialization code found here: https://github.com/BranchMetrics/Smart-App-Banner-Deep-Linking-Web-SDK#manual-installation. If a web session was referred by a Branch link, it will return a JSON dictionary of the associated data for you to act on.

I hope this helps!
